name: pointolio
description: "A new Flutter project."
publish_to: 'none' 

version: 1.1.0+1

environment:
  sdk: ^3.10.3

dependencies:
  cupertino_icons: ^1.0.8
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  share_plus: ^12.0.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.10.5
  drift_dev: ^2.30.1
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  fm_lints:
    git:
      url: https://github.com/fizzymizzy/fm_lints.git
      ref: main
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/font/Rubik-Light.ttf
          weight: 300
        - asset: assets/font/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/Rubik-Regular.ttf
          weight: 400
        - asset: assets/font/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/font/Rubik-Medium.ttf
          weight: 500
        - asset: assets/font/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/font/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/Rubik-Bold.ttf
          weight: 700
        - asset: assets/font/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/font/Rubik-Black.ttf
          weight: 900
        - asset: assets/font/Rubik-BlackItalic.ttf
          weight: 900
          style: italic

flutter_launcher_icons:
  ios: true
  image_path: "assets/logo/logo.png"